### ISSUE TITLE
what happened in 1.11

### ISSUE THREAD

**Issue by Zaydiscool777** [BlockliveScratch/Blocklive#10]
it's not showing me

**Comment by dumorando** [comment]
he added a follow bot

**Comment by MeechaPooch** [comment]
For a few hours, we made the extension force everyone who used it to follow my scratch account. I deleted that change after public outcry.

**Comment by dumorando** [comment]
![image](https://github.com/BlockliveScratch/Blocklive/assets/144301348/6f4d87c7-4acc-4e98-8ec1-9e4eb039f0c0)
bleh
