### ISSUE TITLE
This HAS to be a bug... right?

### ISSUE THREAD

**Issue by ScratchFakemon** [BlockliveScratch/Blocklive#20]
![image](https://github.com/user-attachments/assets/28acdeff-4e37-4ecb-a426-6109cad60125)
# SCRATCH CAT USES BLOCKLIVE??
---
This is probably a testing leftover for the badges or something even earlier where the devs would just use ScratchCat's profile instead of a dedicated profile. But still, it's funny.

**Comment by Waakul** [comment]
You could add badges to users by just adding them as a friend or inviting them to a project, I have fixed it in livescratch tho.

**Comment by ScratchFakemon** [comment]
I actually got LiveScratch a few days ago (before you commented this, I think)... But don't have anyone to test it lol ¯\_(ツ)_/¯
