### ISSUE TITLE
I am offended

### ISSUE THREAD

**Issue by ItsEnderium** [BlockliveScratch/Blocklive#8]
Hey man I'm a big fan of your backdoored extension, only issue is I read badwords.txt and saw "venus mound". I am extremely offended and I need you to fix this massive issue immediately. Also you wrote the N word hard r 3 times in that file, just wanted to point that out lol

**Comment by Roblox-SkyDome** [comment]
> Hey man I'm a big fan of your backdoored extension, only issue is I read badwords.txt and saw "venus mound". I am extremely offended and I need you to fix this massive issue immediately. Also you wrote the N word hard r 3 times in that file, just wanted to point that out lol

He got hacked bro-

**Comment by ItsEnderium** [comment]
> > Hey man I'm a big fan of your backdoored extension, only issue is I read badwords.txt and saw "venus mound". I am extremely offended and I need you to fix this massive issue immediately. Also you wrote the N word hard r 3 times in that file, just wanted to point that out lol
> 
> He got hacked bro-

Unrelated but did you JUST join github

**Comment by BwnnyRxbbit** [comment]
If you are offended by it, stop looking at it.

**Comment by NexusKitten** [comment]
...it's a filter. Of course it's going to have bad words. Plus it's highly unlikely they wrote the filter words themselves, they probably used a list online.

**Comment by Roblox-SkyDome** [comment]
> > > Hey man I'm a big fan of your backdoored extension, only issue is I read badwords.txt and saw "venus mound". I am extremely offended and I need you to fix this massive issue immediately. Also you wrote the N word hard r 3 times in that file, just wanted to point that out lol
> > 
> > 
> > He got hacked bro-
> 
> Unrelated but did you JUST join github

Yes but only because github made e turn on 2FA and now I'm locked out of my main github account. My main account also got falsely banned while I was inactive which resulted in a unban because it was a unfair ban no one warned me about.

**Comment by Roblox-SkyDome** [comment]
> > > > Hey man I'm a big fan of your backdoored extension, only issue is I read badwords.txt and saw "venus mound". I am extremely offended and I need you to fix this massive issue immediately. Also you wrote the N word hard r 3 times in that file, just wanted to point that out lol
> > > 
> > > 
> > > He got hacked bro-
> > 
> > 
> > Unrelated but did you JUST join github
> 
> Yes but only because github made e turn on 2FA and now I'm locked out of my main github account. My main account also got falsely banned while I was inactive which resulted in a unban because it was a unfair ban no one warned me about.

I'm also using this account for a robotic game I'm developing with a actual dev team.

**Comment by ItsEnderium** [comment]
> > > > > Hey man I'm a big fan of your backdoored extension, only issue is I read badwords.txt and saw "venus mound". I am extremely offended and I need you to fix this massive issue immediately. Also you wrote the N word hard r 3 times in that file, just wanted to point that out lol
> > > > 
> > > > 
> > > > He got hacked bro-
> > > 
> > > 
> > > Unrelated but did you JUST join github
> > 
> > 
> > Yes but only because github made e turn on 2FA and now I'm locked out of my main github account. My main account also got falsely banned while I was inactive which resulted in a unban because it was a unfair ban no one warned me about.
> 
> I'm also using this account for a roblox game I'm developing with a actual dev team.

Alr, btw you're wrong about him being hacked https://sites.google.com/view/blocklive/new-blocklive-version

**Comment by jabinstech** [comment]
💀
